# Generated by Django 4.1 on 2022-08-26 23:23

from django.db import migrations, models
import region.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id_region', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region_type', models.CharField(choices=[('NEIGHBORHOOD', 'NEIGHBORHOOD'), ('CITY', 'CITY'), ('STATE', 'STATE')], default=region.enums.RegionType['CITY'], max_length=12)),
                ('postal_code_range_start', models.CharField(max_length=8)),
                ('postal_code_range_end', models.CharField(max_length=8)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
