# Generated by Django 4.1 on 2022-08-29 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='id_region',
        ),
        migrations.AddField(
            model_name='regions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8da09363-058b-44ce-8f09-7b3db9e2af1c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
