# Generated by Django 4.1 on 2022-08-30 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_remove_regions_id_region_regions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('394a314a-8bea-4b65-aa54-2a2b549ac58e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
